travis:
  secure:
    BINSTAR_TOKEN: idBlDSXdZx6TDxwYxpDV0zgMKmDZcPnReWKXqEhh53ILMf87xuytMudzNRWG2lD/9X1XQEfIoGD0JO699quex6quH4gurcG7twez6U85JMybNfbQWxoZaeF21AHzKfK1WCbrzdpaGvn53nBj5AnMiVYc1seF5A6ulv7NdiP8zGRHdjhNP9s5L60E4ACSDLspauWyzjvae+ggBvVxtnJ9512nE/rxWrH+0jmGg5MMB5CBaE/d+VbU5iWtnz29FmmUj3hgL15GrJae4dxyXV88AK7VxZcuNYlsRv0+1G5v1lQbwyzFldBUrenw6ExU94cuAXDgegqsEKHAhPCvmqfMj3Eg9Xxy0J2Nc+X3JQWlDXJZv3kB/v30EnKBW2WyOdek7/BtelevMOqR52I0ntJRkCqOcCk4NUU2J6dfGVwMBdgHVQsVbmCovR4MFUxShl2TCsMrtil2TPM7iJSsMdJYoNF/XDhKy8iFuBA6Cb9wHE+pCHS+IMYISuGJNOFYGzIZIDAGcIgC6NxGtBM73nrY5y5T+MebI7nVjRYzXdYoCvr2u+iciOPcb52BhxFUTq6zbSJ5QqEmsxZxJ/GkoSlGm0e73zuxOOAFIUiqc5808+YDMF2c1Jn4BB9l+d1gOuNZgBo3e+WZtphdU6O5Hw8XQFjeWvIJ43lHvoIwRzhEqhE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
